### ISSUE TITLE
Simulator allows discarding at 8 clues

### ISSUE THREAD

**Issue by timotree3** [WuTheFWasThat/hanabi.rs#14]
The Hanabi rules in my copy ([PDF here](https://rnrgames.com/Content/RRGames/images/ProductRules/hanabiRules.PDF)) and the ones implemented on hanab.live agree that discarding at 8 clues is not allowed. The simulator does not implement this functionality, and the strategies seem to be making use of this: both the cheating and information strategies discarded at 8 clues in the first game I tested with each. This should be simple enough to fix but it may reduce the effectiveness of the strategies

**Comment by WuTheFWasThat** [comment]
oh wow, good catch.  fixing and rerunning results seems good.  hopefully doesnt affect things too much

**Comment by timotree3** [comment]
:+1: I'll make a PR
