### ISSUE TITLE
The information strategy seems nondeterministic and I don't know why

### ISSUE THREAD

**Issue by felixbauckholt** [WuTheFWasThat/hanabi.rs#8]
I only now noticed that when running the strategy with `-n 10000 -s 0 -t 4 -p 5 -g info`, the score histogram varies very slightly between different runs. This behavior goes as far back as commit 7370859, and does not change when I run with one thread instead of four.

Do you have any guesses what could be causing this? Floating-point stuff would explain different behavior across versions that "should" be equivalent, but it doesn't seem to explain why behavior would be different across runs of the same code. I heard that HashMaps randomize something for security reasons, but I'm not sure if that would plausibly affect the strategy, and I also don't know how to turn off that feature and make all HashMaps deterministic.

Am I likely to miss other causes of nondeterminism? Are there any tricks to make win-rates reproducible exactly?

**Comment by WuTheFWasThat** [comment]
thanks for the report!  I don't have any good guesses as to why, either

**Comment by felixbauckholt** [comment]
After staring at my debugger for a bit, yes it seems to be the `HashMap`s. I haven't found any "switch" that turns off the nondeterministic behavior, but replacing all `HashMap`s with `FnvHashMap`s seems to help. (They're also supposed to be faster or something?)

I also succumbed to the urge to write a script to automate updating the README. If you're OK with this being in `main.rs`, I could use it to rebase #7 with the Correct™️ numbers! :D

Ohh also I computed the first 20000 seeds instead of 10000, since that still keeps the runtime of my script below 10m. Are you OK with this? Do you prefer more or less precision?

**Comment by WuTheFWasThat** [comment]
oh and, 20K seeds is fine!  

I was thinking we should probably also output the estimated stdev of the sampled statistic.  I think it's just stdev(samples) / sqrt(n-1).  then we can have a better sense for how many seeds we should be using, and how useful it is to double in the current regime and stuff
